package com.alistair.mappart

import java.sql.Timestamp

data class TreeInfo(
    val id: Long,
    val treeName: String,
    val city: String,
    val ward: String,
    val street: String,
    val createdOn: Timestamp,
    val modifiedOn: Timestamp,
    val createdBy: String,
    val modifiedBy: String,
    val latitude: String,
    val longitude: String,
    val locationAccuracy: String,
    val species: String,
    val localName: String,
    val DBH: String,
    val height: Double,
    val spread: Double,
    val form: String,
    val siteTopography: String,
    val otherSiteTopography: String,
    val rootSurfaceType: String,
    val rootSurfaceValue: String,
    val foilageColor: String,
    val foilageDensity: String,
    val vigorClass: String,
    val treesDefects: String,
    val partLikelyFail: String,
    val targetUnderTree: String,
    val canBeMoved: Boolean,
    val occupancy: String,
    val hazardRating: String,
    val hazardAbatement: String,
    val remarks: String,
    val imagePath: String,
)